"""create_initial_models

Revision ID: a8b9498ede6a
Revises: 
Create Date: 2026-09-08 09:13:40.903096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a8b9498ede6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_reference', sa.String(length=100), nullable=False, comment='Authoritative identifier / citizen registry reference / masked tax ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Legal name of owner or institutional entity'),
    sa.Column('contact_reference', sa.String(length=255), nullable=True, comment='Contact detail reference or secure address record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_owner_reference'), 'owners', ['owner_reference'], unique=True)
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False, comment='Unique identifier for the cadastral parcel'),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('tehsil', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area_sq_m', sa.Numeric(precision=12, scale=2), nullable=True, comment='Total surveyed ground parcel area in square meters'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='2D boundary polygon of the land parcel in EPSG:4326'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parcels_geometry', 'parcels', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_parcels_parcel_id'), 'parcels', ['parcel_id'], unique=True)
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=False, comment='Unique identifier for the building entity'),
    sa.Column('parcel_id', sa.UUID(), nullable=False, comment='Foreign key linking to parent cadastral parcel'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name or designation of the building / tower'),
    sa.Column('building_type', sa.String(length=100), nullable=True, comment='Classification e.g., Residential, Commercial, Mixed-use, Industrial'),
    sa.Column('total_floors', sa.Integer(), nullable=True, comment='Total count of floors including basements'),
    sa.Column('height_m', sa.Numeric(precision=8, scale=2), nullable=True, comment='Total architectural height of the structure in meters'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='2D footprint polygon of the building on the parcel (EPSG:4326)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buildings_geometry', 'buildings', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_buildings_building_id'), 'buildings', ['building_id'], unique=True)
    op.create_index(op.f('ix_buildings_parcel_id'), 'buildings', ['parcel_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False, comment='Foreign key linking to parent building'),
    sa.Column('floor_number', sa.Integer(), nullable=False, comment='Sequential floor level number (negative for basements, 0 for ground, 1..N for upper floors)'),
    sa.Column('floor_name', sa.String(length=100), nullable=True, comment='Descriptive floor label e.g., Basement 1, Ground Floor, Mezzanine, 5th Floor'),
    sa.Column('elevation_m', sa.Numeric(precision=8, scale=2), nullable=True, comment='Base vertical elevation above mean sea level or ground datum in meters'),
    sa.Column('height_m', sa.Numeric(precision=8, scale=2), nullable=True, comment='Floor-to-ceiling clear height in meters'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='2D spatial boundary / floor plate polygon in EPSG:4326'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor_number', name='uq_building_floor_number')
    )
    op.create_index('idx_floors_geometry', 'floors', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_floors_building_id'), 'floors', ['building_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False, comment='Foreign key linking to parent building'),
    sa.Column('floor_id', sa.UUID(), nullable=False, comment='Foreign key linking to specific floor level'),
    sa.Column('unit_code', sa.String(length=100), nullable=False, comment='Unit identifier e.g., Flat 402, Shop G-12, Parking P2-45'),
    sa.Column('unit_type', sa.String(length=50), nullable=True, comment='Category: Apartment, Commercial Suite, Shop, Parking Bay, Utility'),
    sa.Column('area_sq_m', sa.Numeric(precision=10, scale=2), nullable=True, comment='Carpet / volumetric floor area of the unit in square meters'),
    sa.Column('usage_type', sa.String(length=50), nullable=True, comment='Functional usage: Residential, Retail, Office, Storage, Vehicle Parking'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='GEOMETRYZ', srid=4326, dimension=3, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='3D volumetric spatial geometry (POLYGONZ / POLYHEDRALSURFACEZ in EPSG:4326)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'unit_code', name='uq_floor_unit_code')
    )
    op.create_index('idx_units_geometry', 'units', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_units_building_id'), 'units', ['building_id'], unique=False)
    op.create_index(op.f('ix_units_floor_id'), 'units', ['floor_id'], unique=False)
    op.create_index(op.f('ix_units_unit_code'), 'units', ['unit_code'], unique=False)
    op.create_table('ownership_rights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False, comment='Foreign key linking to volumetric unit'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Foreign key linking to owner'),
    sa.Column('right_type', sa.String(length=50), nullable=False, comment='Type of property tenure: Freehold, Leasehold, Tenancy, Mortgage, Easement'),
    sa.Column('ownership_percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Percentage share of ownership interest (0.01 to 100.00)'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='Commencement timestamp of the property tenure / title deed'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='Expiration timestamp for leasehold or temporary tenure rights'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_rights_owner_id'), 'ownership_rights', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ownership_rights_unit_id'), 'ownership_rights', ['unit_id'], unique=False)
    op.create_table('ulpin_3d_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False, comment='Foreign key linking 1-to-1 with volumetric unit'),
    sa.Column('ulpin_3d', sa.String(length=64), nullable=False, comment='Algorithmic 3D Unique Land Parcel Identification Number'),
    sa.Column('parcel_id_reference', sa.String(length=64), nullable=False, comment='Authoritative parent parcel identifier reference'),
    sa.Column('building_id_reference', sa.String(length=64), nullable=False, comment='Authoritative parent building identifier reference'),
    sa.Column('floor_number', sa.Integer(), nullable=False, comment='Vertical level index of the unit'),
    sa.Column('unit_code', sa.String(length=100), nullable=False, comment='Unit reference code within floor/building'),
    sa.Column('unit_type', sa.String(length=50), nullable=True, comment='Unit classification e.g. Flat, Commercial, Parking'),
    sa.Column('generation_version', sa.String(length=20), nullable=False, comment='ULPIN standard generation algorithm specification version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ulpin_3d_records_building_id_reference'), 'ulpin_3d_records', ['building_id_reference'], unique=False)
    op.create_index(op.f('ix_ulpin_3d_records_parcel_id_reference'), 'ulpin_3d_records', ['parcel_id_reference'], unique=False)
    op.create_index(op.f('ix_ulpin_3d_records_ulpin_3d'), 'ulpin_3d_records', ['ulpin_3d'], unique=True)
    op.create_index(op.f('ix_ulpin_3d_records_unit_code'), 'ulpin_3d_records', ['unit_code'], unique=False)
    op.create_index(op.f('ix_ulpin_3d_records_unit_id'), 'ulpin_3d_records', ['unit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ulpin_3d_records_unit_id'), table_name='ulpin_3d_records')
    op.drop_index(op.f('ix_ulpin_3d_records_unit_code'), table_name='ulpin_3d_records')
    op.drop_index(op.f('ix_ulpin_3d_records_ulpin_3d'), table_name='ulpin_3d_records')
    op.drop_index(op.f('ix_ulpin_3d_records_parcel_id_reference'), table_name='ulpin_3d_records')
    op.drop_index(op.f('ix_ulpin_3d_records_building_id_reference'), table_name='ulpin_3d_records')
    op.drop_table('ulpin_3d_records')
    op.drop_index(op.f('ix_ownership_rights_unit_id'), table_name='ownership_rights')
    op.drop_index(op.f('ix_ownership_rights_owner_id'), table_name='ownership_rights')
    op.drop_table('ownership_rights')
    op.drop_index(op.f('ix_units_unit_code'), table_name='units')
    op.drop_index(op.f('ix_units_floor_id'), table_name='units')
    op.drop_index(op.f('ix_units_building_id'), table_name='units')
    op.drop_index('idx_units_geometry', table_name='units', postgresql_using='gist')
    op.drop_table('units')
    op.drop_index(op.f('ix_floors_building_id'), table_name='floors')
    op.drop_index('idx_floors_geometry', table_name='floors', postgresql_using='gist')
    op.drop_table('floors')
    op.drop_index(op.f('ix_buildings_parcel_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_building_id'), table_name='buildings')
    op.drop_index('idx_buildings_geometry', table_name='buildings', postgresql_using='gist')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_parcels_parcel_id'), table_name='parcels')
    op.drop_index('idx_parcels_geometry', table_name='parcels', postgresql_using='gist')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_owners_owner_reference'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
