"""create_blueprint_tables

Revision ID: ec0da828dce2
Revises: 9a5a5ce827bb
Create Date: 2026-09-24 19:19:41.945445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ec0da828dce2'
down_revision: Union[str, Sequence[str], None] = '9a5a5ce827bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False, comment='Cadastral parcel containing the building'),
    sa.Column('building_id', sa.UUID(), nullable=False, comment='Target building entity'),
    sa.Column('uploaded_by', sa.UUID(), nullable=False, comment='User/Official who submitted the blueprint'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original client filename'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='Sanitized server-side storage filename'),
    sa.Column('file_type', sa.String(length=100), nullable=False, comment='MIME type of uploaded file (e.g. application/pdf, image/png)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA-256 cryptographic digest of document content'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='blueprintstatus', native_enum=False, length=20), nullable=False, comment='Lifecycle status: PENDING, APPROVED, REJECTED'),
    sa.Column('description', sa.Text(), nullable=True, comment='Official submission notes or remarks'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True, comment='Official or Admin who reviewed the blueprint'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when review was finalized'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Explanation provided when blueprint is rejected'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_blueprints_building_id'), 'blueprints', ['building_id'], unique=False)
    op.create_index(op.f('ix_blueprints_parcel_id'), 'blueprints', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_blueprints_status'), 'blueprints', ['status'], unique=False)
    op.create_index(op.f('ix_blueprints_uploaded_by'), 'blueprints', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_blueprints_verified_by'), 'blueprints', ['verified_by'], unique=False)
    op.create_table('blueprint_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action performed: UPLOADED, APPROVED, REJECTED'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True, comment='Additional context or notes for the activity'),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_activities_blueprint_id'), 'blueprint_activities', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_activities_user_id'), 'blueprint_activities', ['user_id'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full legal name of the user',
               existing_comment='Full legal name of the citizen, official, or administrator',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Authoritative email address used for authentication',
               existing_comment='Unique official or citizen email address',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Secure bcrypt hashed password',
               existing_comment='Bcrypt-hashed password string',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='User role: CITIZEN, OFFICIAL, ADMIN',
               existing_comment='Institutional role: CITIZEN, OFFICIAL, ADMIN',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Institutional role: CITIZEN, OFFICIAL, ADMIN',
               existing_comment='User role: CITIZEN, OFFICIAL, ADMIN',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt-hashed password string',
               existing_comment='Secure bcrypt hashed password',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique official or citizen email address',
               existing_comment='Authoritative email address used for authentication',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full legal name of the citizen, official, or administrator',
               existing_comment='Full legal name of the user',
               existing_nullable=False)
    op.drop_index(op.f('ix_blueprint_activities_user_id'), table_name='blueprint_activities')
    op.drop_index(op.f('ix_blueprint_activities_blueprint_id'), table_name='blueprint_activities')
    op.drop_table('blueprint_activities')
    op.drop_index(op.f('ix_blueprints_verified_by'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_uploaded_by'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_status'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_parcel_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_building_id'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
